// Code generated by gen/gen.mjs from @factory/droid-sdk 0.9.1. DO NOT EDIT.

package protocol

import (
	"encoding/json"
	"time"
)

// SDKVersion is the @factory/droid-sdk release the protocol was generated from.
const SDKVersion = "0.9.1"

// FactoryProtocolVersion is the protocol version requests carry.
const FactoryProtocolVersion = "1.201.1"

// Methods the Client calls on the Daemon.
const (
	MethodAuthenticate                       = "daemon.authenticate"
	MethodLogout                             = "daemon.logout"
	MethodInitializeSession                  = "daemon.initialize_session"
	MethodLoadSession                        = "daemon.load_session"
	MethodAddUserMessage                     = "daemon.add_user_message"
	MethodResolveQueuedUserMessage           = "daemon.resolve_queued_user_message"
	MethodInterruptSession                   = "daemon.interrupt_session"
	MethodCloseSession                       = "daemon.close_session"
	MethodKillWorkerSession                  = "daemon.kill_worker_session"
	MethodListOpenedSessions                 = "daemon.list_opened_sessions"
	MethodListAvailableSessions              = "daemon.list_available_sessions"
	MethodListModels                         = "daemon.list_models"
	MethodGetSessionMessages                 = "daemon.get_session_messages"
	MethodUpdateSessionSettings              = "daemon.update_session_settings"
	MethodChangeWorkingDirectory             = "daemon.change_working_directory"
	MethodValidateWorkingDirectory           = "daemon.validate_working_directory"
	MethodCheckFolderTrust                   = "daemon.check_folder_trust"
	MethodTrustFolder                        = "daemon.trust_folder"
	MethodGetDefaultSettings                 = "daemon.get_default_settings"
	MethodUpdateSessionDefaults              = "daemon.update_session_defaults"
	MethodListCustomModels                   = "daemon.list_custom_models"
	MethodUpsertCustomModel                  = "daemon.upsert_custom_model"
	MethodDeleteCustomModel                  = "daemon.delete_custom_model"
	MethodTriggerUpdate                      = "daemon.trigger_update"
	MethodInstallSSHKey                      = "daemon.install_ssh_key"
	MethodRelayStart                         = "daemon.relay.start"
	MethodRelayStop                          = "daemon.relay.stop"
	MethodRelayGetStatus                     = "daemon.relay.get_status"
	MethodCreateTerminal                     = "daemon.create_terminal"
	MethodWriteTerminalData                  = "daemon.write_terminal_data"
	MethodResizeTerminal                     = "daemon.resize_terminal"
	MethodCloseTerminal                      = "daemon.close_terminal"
	MethodListTerminals                      = "daemon.list_terminals"
	MethodListFiles                          = "daemon.list_files"
	MethodSearchFiles                        = "daemon.search_files"
	MethodSearchSessions                     = "daemon.search_sessions"
	MethodGetMCPConfig                       = "daemon.get_mcp_config"
	MethodUpdateMCPConfig                    = "daemon.update_mcp_config"
	MethodToggleMCPServer                    = "daemon.toggle_mcp_server"
	MethodAuthenticateMCPServer              = "daemon.authenticate_mcp_server"
	MethodClearMCPAuth                       = "daemon.clear_mcp_auth"
	MethodCancelMCPAuth                      = "daemon.cancel_mcp_auth"
	MethodAddMCPServer                       = "daemon.add_mcp_server"
	MethodRemoveMCPServer                    = "daemon.remove_mcp_server"
	MethodListMCPRegistry                    = "daemon.list_mcp_registry"
	MethodListMCPTools                       = "daemon.list_mcp_tools"
	MethodListMCPServers                     = "daemon.list_mcp_servers"
	MethodToggleMCPTool                      = "daemon.toggle_mcp_tool"
	MethodSubmitMCPAuthCode                  = "daemon.submit_mcp_auth_code"
	MethodSubmitMCPAuthError                 = "daemon.submit_mcp_auth_error"
	MethodArchiveSession                     = "daemon.archive_session"
	MethodUnarchiveSession                   = "daemon.unarchive_session"
	MethodRenameSession                      = "daemon.rename_session"
	MethodListSkills                         = "daemon.list_skills"
	MethodSetSkillDisabled                   = "daemon.set_skill_disabled"
	MethodListCommands                       = "daemon.list_commands"
	MethodListAvailablePlugins               = "daemon.list_available_plugins"
	MethodListInstalledPlugins               = "daemon.list_installed_plugins"
	MethodInstallPlugin                      = "daemon.install_plugin"
	MethodUninstallPlugin                    = "daemon.uninstall_plugin"
	MethodSetPluginEnabled                   = "daemon.set_plugin_enabled"
	MethodUpdatePlugin                       = "daemon.update_plugin"
	MethodListMarketplaces                   = "daemon.list_marketplaces"
	MethodAddMarketplace                     = "daemon.add_marketplace"
	MethodRemoveMarketplace                  = "daemon.remove_marketplace"
	MethodUpdateMarketplace                  = "daemon.update_marketplace"
	MethodSubmitBugReport                    = "daemon.submit_bug_report"
	MethodGetRewindInfo                      = "daemon.get_rewind_info"
	MethodExecuteRewind                      = "daemon.execute_rewind"
	MethodCompactSession                     = "daemon.compact_session"
	MethodForkSession                        = "daemon.fork_session"
	MethodGetContextBreakdown                = "daemon.get_context_breakdown"
	MethodListWorktreeSetupProfiles          = "daemon.list_worktree_setup_profiles"
	MethodSaveWorktreeSetupProfile           = "daemon.save_worktree_setup_profile"
	MethodDeleteWorktreeSetupProfile         = "daemon.delete_worktree_setup_profile"
	MethodListManagedWorktrees               = "daemon.list_managed_worktrees"
	MethodCleanupWorktree                    = "daemon.cleanup_worktree"
	MethodInspectWorktreeDeletion            = "daemon.inspect_worktree_deletion"
	MethodListAutomations                    = "daemon.list_automations"
	MethodRunAutomation                      = "daemon.run_automation"
	MethodPauseAutomation                    = "daemon.pause_automation"
	MethodResumeAutomation                   = "daemon.resume_automation"
	MethodGetAutomationHistory               = "daemon.get_automation_history"
	MethodGetAutomationVisual                = "daemon.get_automation_visual"
	MethodCreateAutomation                   = "daemon.create_automation"
	MethodUpdateAutomationModel              = "daemon.update_automation_model"
	MethodUpdateAutomationPrivacy            = "daemon.update_automation_privacy"
	MethodUpdateAutomationPrompt             = "daemon.update_automation_prompt"
	MethodUpdateAutomationSchedule           = "daemon.update_automation_schedule"
	MethodRenameAutomation                   = "daemon.rename_automation"
	MethodDeleteAutomation                   = "daemon.delete_automation"
	MethodForkAutomation                     = "daemon.fork_automation"
	MethodApplyAutomationConfig              = "daemon.apply_automation_config"
	MethodUpdateAutomation                   = "daemon.update_automation"
	MethodSfListWorkstreams                  = "daemon.sf.list_workstreams"
	MethodSfGetWorkstream                    = "daemon.sf.get_workstream"
	MethodSfCreateWorkstream                 = "daemon.sf.create_workstream"
	MethodSfUpdateWorkstream                 = "daemon.sf.update_workstream"
	MethodSfDeleteWorkstream                 = "daemon.sf.delete_workstream"
	MethodSfPublishWorkstreamContent         = "daemon.sf.publish_workstream_content"
	MethodSfHydrateWorkstreamContent         = "daemon.sf.hydrate_workstream_content"
	MethodSfListSignals                      = "daemon.sf.list_signals"
	MethodSfListChanges                      = "daemon.sf.list_changes"
	MethodSfListActivities                   = "daemon.sf.list_activities"
	MethodSfResolveActivityReview            = "daemon.sf.resolve_activity_review"
	MethodSfListEvents                       = "daemon.sf.list_events"
	MethodSfMarkEventsRead                   = "daemon.sf.mark_events_read"
	MethodSfMarkEventsUnread                 = "daemon.sf.mark_events_unread"
	MethodListCrons                          = "daemon.list_crons"
	MethodCreateCron                         = "daemon.create_cron"
	MethodUpdateCron                         = "daemon.update_cron"
	MethodDeleteCron                         = "daemon.delete_cron"
	MethodHoldSessionCrons                   = "daemon.hold_session_crons"
	MethodResumeSessionCrons                 = "daemon.resume_session_crons"
	MethodGetGitDiff                         = "daemon.get_git_diff"
	MethodListGitBranches                    = "daemon.list_git_branches"
	MethodCheckoutGitBranch                  = "daemon.checkout_git_branch"
	MethodResolvePullRequestStatuses         = "daemon.resolve_pull_request_statuses"
	MethodGetGitBranchDivergence             = "daemon.get_git_branch_divergence"
	MethodInspectMissionReadiness            = "daemon.inspect_mission_readiness"
	MethodAcknowledgeMissionReadinessWarning = "daemon.acknowledge_mission_readiness_warning"
	MethodGitPush                            = "daemon.git_push"
	MethodGitCommit                          = "daemon.git_commit"
	MethodCreatePR                           = "daemon.create_pr"
	MethodGetSemanticDiffCache               = "daemon.get_semantic_diff_cache"
	MethodSaveSemanticDiffCache              = "daemon.save_semantic_diff_cache"
	MethodGenerateSemanticDiff               = "daemon.generate_semantic_diff"
	MethodGetProxyToken                      = "daemon.get_proxy_token"
	MethodGetWorkspaceFileContent            = "daemon.get_workspace_file_content"
	MethodWriteWorkspaceFileContent          = "daemon.write_workspace_file_content"
	MethodPushCwdFileToURL                   = "daemon.push_cwd_file_to_url"
	MethodPullURLToCwdFile                   = "daemon.pull_url_to_cwd_file"
)

// Notifications the Daemon sends.
const (
	NotificationConnectionStatus           = "daemon.connection_status"
	NotificationCronStateChanged           = "daemon.cron.state_changed"
	NotificationSessionArchiveStateChanged = "daemon.session.archive_state_changed"
	NotificationSessionSetupStepProgress   = "daemon.session.setup_step_progress"
	NotificationSessionOptimisticMessage   = "daemon.session.optimistic_message"
	NotificationWorktreeBranchChanged      = "daemon.worktree.branch_changed"
	NotificationWorktreeRemoved            = "daemon.worktree.removed"
	NotificationSessionNotification        = "daemon.session_notification"
	NotificationRelayStatusChanged         = "daemon.relay.status_changed"
)

// Requests the Daemon sends the Client, which it must answer.
const (
	ServerRequestWarmupCache       = "daemon.warmup_cache"
	ServerRequestRequestPermission = "daemon.request_permission"
	ServerRequestAskUser           = "daemon.ask_user"
)

// MethodInfo is how a method is answered.
type MethodInfo struct {
	// Ack: the Daemon may answer {"accepted": true} at once and complete the
	// request later with a session notification of type CompletedBy that
	// carries the request's id.
	Ack         bool
	CompletedBy string
	// Timeout replaces the Client's default request timeout when not 0.
	Timeout time.Duration
}

// NewParams returns a pointer to a new value of a method's params type, or
// nil for an unknown method.
func NewParams(method string) any {
	switch method {
	case MethodAuthenticate:
		return new(AuthenticateParams)
	case MethodInitializeSession:
		return new(InitializeSessionParams)
	case MethodLoadSession:
		return new(LoadSessionParams)
	case MethodAddUserMessage:
		return new(AddUserMessageParams)
	case MethodResolveQueuedUserMessage:
		return new(json.RawMessage)
	case MethodInterruptSession:
		return new(InterruptSessionParams)
	case MethodCloseSession:
		return new(CloseSessionParams)
	case MethodKillWorkerSession:
		return new(KillWorkerSessionParams)
	case MethodListOpenedSessions:
		return new(ListOpenedSessionsParams)
	case MethodListAvailableSessions:
		return new(ListAvailableSessionsParams)
	case MethodListModels:
		return new(ListModelsParams)
	case MethodGetSessionMessages:
		return new(GetSessionMessagesParams)
	case MethodUpdateSessionSettings:
		return new(UpdateSessionSettingsParams)
	case MethodChangeWorkingDirectory:
		return new(ChangeWorkingDirectoryParams)
	case MethodValidateWorkingDirectory:
		return new(ValidateWorkingDirectoryParams)
	case MethodCheckFolderTrust:
		return new(CheckFolderTrustParams)
	case MethodTrustFolder:
		return new(TrustFolderParams)
	case MethodUpdateSessionDefaults:
		return new(UpdateSessionDefaultsParams)
	case MethodUpsertCustomModel:
		return new(UpsertCustomModelParams)
	case MethodDeleteCustomModel:
		return new(DeleteCustomModelParams)
	case MethodInstallSSHKey:
		return new(InstallSSHKeyParams)
	case MethodCreateTerminal:
		return new(CreateTerminalParams)
	case MethodWriteTerminalData:
		return new(WriteTerminalDataParams)
	case MethodResizeTerminal:
		return new(ResizeTerminalParams)
	case MethodCloseTerminal:
		return new(CloseTerminalParams)
	case MethodListTerminals:
		return new(ListTerminalsParams)
	case MethodListFiles:
		return new(ListFilesParams)
	case MethodSearchFiles:
		return new(SearchFilesParams)
	case MethodSearchSessions:
		return new(SearchSessionsParams)
	case MethodUpdateMCPConfig:
		return new(UpdateMCPConfigParams)
	case MethodToggleMCPServer:
		return new(ToggleMCPServerParams)
	case MethodAuthenticateMCPServer:
		return new(AuthenticateMCPServerParams)
	case MethodClearMCPAuth:
		return new(ClearMCPAuthParams)
	case MethodCancelMCPAuth:
		return new(CancelMCPAuthParams)
	case MethodAddMCPServer:
		return new(AddMCPServerParams)
	case MethodRemoveMCPServer:
		return new(RemoveMCPServerParams)
	case MethodListMCPRegistry:
		return new(ListMCPRegistryParams)
	case MethodListMCPTools:
		return new(ListMCPToolsParams)
	case MethodListMCPServers:
		return new(ListMCPServersParams)
	case MethodToggleMCPTool:
		return new(ToggleMCPToolParams)
	case MethodSubmitMCPAuthCode:
		return new(SubmitMCPAuthCodeParams)
	case MethodSubmitMCPAuthError:
		return new(SubmitMCPAuthErrorParams)
	case MethodArchiveSession:
		return new(ArchiveSessionParams)
	case MethodUnarchiveSession:
		return new(UnarchiveSessionParams)
	case MethodRenameSession:
		return new(RenameSessionParams)
	case MethodListSkills:
		return new(ListSkillsParams)
	case MethodSetSkillDisabled:
		return new(SetSkillDisabledParams)
	case MethodListCommands:
		return new(ListCommandsParams)
	case MethodListAvailablePlugins:
		return new(ListAvailablePluginsParams)
	case MethodListInstalledPlugins:
		return new(ListInstalledPluginsParams)
	case MethodInstallPlugin:
		return new(InstallPluginParams)
	case MethodUninstallPlugin:
		return new(UninstallPluginParams)
	case MethodSetPluginEnabled:
		return new(SetPluginEnabledParams)
	case MethodUpdatePlugin:
		return new(UpdatePluginParams)
	case MethodListMarketplaces:
		return new(ListMarketplacesParams)
	case MethodAddMarketplace:
		return new(AddMarketplaceParams)
	case MethodRemoveMarketplace:
		return new(RemoveMarketplaceParams)
	case MethodUpdateMarketplace:
		return new(UpdateMarketplaceParams)
	case MethodSubmitBugReport:
		return new(SubmitBugReportParams)
	case MethodGetRewindInfo:
		return new(GetRewindInfoParams)
	case MethodExecuteRewind:
		return new(ExecuteRewindParams)
	case MethodCompactSession:
		return new(CompactSessionParams)
	case MethodForkSession:
		return new(ForkSessionParams)
	case MethodGetContextBreakdown:
		return new(GetContextBreakdownParams)
	case MethodListWorktreeSetupProfiles:
		return new(ListWorktreeSetupProfilesParams)
	case MethodSaveWorktreeSetupProfile:
		return new(SaveWorktreeSetupProfileParams)
	case MethodDeleteWorktreeSetupProfile:
		return new(DeleteWorktreeSetupProfileParams)
	case MethodListManagedWorktrees:
		return new(ListManagedWorktreesParams)
	case MethodCleanupWorktree:
		return new(CleanupWorktreeParams)
	case MethodInspectWorktreeDeletion:
		return new(InspectWorktreeDeletionParams)
	case MethodListAutomations:
		return new(ListAutomationsParams)
	case MethodRunAutomation:
		return new(RunAutomationParams)
	case MethodPauseAutomation:
		return new(PauseAutomationParams)
	case MethodResumeAutomation:
		return new(ResumeAutomationParams)
	case MethodGetAutomationHistory:
		return new(GetAutomationHistoryParams)
	case MethodGetAutomationVisual:
		return new(GetAutomationVisualParams)
	case MethodCreateAutomation:
		return new(CreateAutomationParams)
	case MethodUpdateAutomationModel:
		return new(UpdateAutomationModelParams)
	case MethodUpdateAutomationPrivacy:
		return new(UpdateAutomationPrivacyParams)
	case MethodUpdateAutomationPrompt:
		return new(UpdateAutomationPromptParams)
	case MethodUpdateAutomationSchedule:
		return new(UpdateAutomationScheduleParams)
	case MethodRenameAutomation:
		return new(RenameAutomationParams)
	case MethodDeleteAutomation:
		return new(DeleteAutomationParams)
	case MethodForkAutomation:
		return new(ForkAutomationParams)
	case MethodApplyAutomationConfig:
		return new(ApplyAutomationConfigParams)
	case MethodUpdateAutomation:
		return new(UpdateAutomationParams)
	case MethodSfListWorkstreams:
		return new(SfListWorkstreamsParams)
	case MethodSfGetWorkstream:
		return new(SfGetWorkstreamParams)
	case MethodSfCreateWorkstream:
		return new(SfCreateWorkstreamParams)
	case MethodSfUpdateWorkstream:
		return new(SfUpdateWorkstreamParams)
	case MethodSfDeleteWorkstream:
		return new(SfDeleteWorkstreamParams)
	case MethodSfPublishWorkstreamContent:
		return new(SfPublishWorkstreamContentParams)
	case MethodSfHydrateWorkstreamContent:
		return new(SfHydrateWorkstreamContentParams)
	case MethodSfListSignals:
		return new(SfListSignalsParams)
	case MethodSfListChanges:
		return new(SfListChangesParams)
	case MethodSfListActivities:
		return new(SfListActivitiesParams)
	case MethodSfResolveActivityReview:
		return new(SfResolveActivityReviewParams)
	case MethodSfListEvents:
		return new(SfListEventsParams)
	case MethodSfMarkEventsRead:
		return new(SfMarkEventsReadParams)
	case MethodSfMarkEventsUnread:
		return new(SfMarkEventsUnreadParams)
	case MethodListCrons:
		return new(ListCronsParams)
	case MethodCreateCron:
		return new(DaemonCreateCronRequestParams)
	case MethodUpdateCron:
		return new(UpdateCronParams)
	case MethodDeleteCron:
		return new(DeleteCronParams)
	case MethodHoldSessionCrons:
		return new(HoldSessionCronsParams)
	case MethodResumeSessionCrons:
		return new(ResumeSessionCronsParams)
	case MethodGetGitDiff:
		return new(GetGitDiffParams)
	case MethodListGitBranches:
		return new(ListGitBranchesParams)
	case MethodCheckoutGitBranch:
		return new(CheckoutGitBranchParams)
	case MethodResolvePullRequestStatuses:
		return new(ResolvePullRequestStatusesParams)
	case MethodGetGitBranchDivergence:
		return new(GetGitBranchDivergenceParams)
	case MethodInspectMissionReadiness:
		return new(InspectMissionReadinessParams)
	case MethodAcknowledgeMissionReadinessWarning:
		return new(AcknowledgeMissionReadinessWarningParams)
	case MethodGitPush:
		return new(GitPushParams)
	case MethodGitCommit:
		return new(GitCommitParams)
	case MethodCreatePR:
		return new(CreatePRParams)
	case MethodGetSemanticDiffCache:
		return new(GetSemanticDiffCacheParams)
	case MethodSaveSemanticDiffCache:
		return new(SaveSemanticDiffCacheParams)
	case MethodGenerateSemanticDiff:
		return new(GenerateSemanticDiffParams)
	case MethodGetProxyToken:
		return new(json.RawMessage)
	case MethodGetWorkspaceFileContent:
		return new(GetWorkspaceFileContentParams)
	case MethodWriteWorkspaceFileContent:
		return new(WriteWorkspaceFileContentParams)
	case MethodPushCwdFileToURL:
		return new(PushCwdFileToURLParams)
	case MethodPullURLToCwdFile:
		return new(PullURLToCwdFileParams)
	}
	return nil
}

// NewResult returns a pointer to a new value of a method's result type, or
// nil for an unknown method.
func NewResult(method string) any {
	switch method {
	case MethodAuthenticate:
		return new(AuthenticateResult)
	case MethodLogout:
		return new(LogoutResult)
	case MethodInitializeSession:
		return new(InitializeSessionResult)
	case MethodLoadSession:
		return new(LoadSessionResult)
	case MethodAddUserMessage:
		return new(AddUserMessageResult)
	case MethodResolveQueuedUserMessage:
		return new(ResolveQueuedUserMessageResult)
	case MethodInterruptSession:
		return new(InterruptSessionResult)
	case MethodCloseSession:
		return new(CloseSessionResult)
	case MethodKillWorkerSession:
		return new(KillWorkerSessionResult)
	case MethodListOpenedSessions:
		return new(ListOpenedSessionsResult)
	case MethodListAvailableSessions:
		return new(ListAvailableSessionsResult)
	case MethodListModels:
		return new(ListModelsResult)
	case MethodGetSessionMessages:
		return new(GetSessionMessagesResult)
	case MethodUpdateSessionSettings:
		return new(UpdateSessionSettingsResult)
	case MethodChangeWorkingDirectory:
		return new(ChangeWorkingDirectoryResult)
	case MethodValidateWorkingDirectory:
		return new(ValidateWorkingDirectoryResult)
	case MethodCheckFolderTrust:
		return new(CheckFolderTrustResult)
	case MethodTrustFolder:
		return new(TrustFolderResult)
	case MethodGetDefaultSettings:
		return new(GetDefaultSettingsResult)
	case MethodUpdateSessionDefaults:
		return new(UpdateSessionDefaultsResult)
	case MethodListCustomModels:
		return new(ListCustomModelsResult)
	case MethodUpsertCustomModel:
		return new(UpsertCustomModelResult)
	case MethodDeleteCustomModel:
		return new(DeleteCustomModelResult)
	case MethodTriggerUpdate:
		return new(TriggerUpdateResult)
	case MethodInstallSSHKey:
		return new(InstallSSHKeyResult)
	case MethodRelayStart:
		return new(RelayStartResult)
	case MethodRelayStop:
		return new(RelayStopResult)
	case MethodRelayGetStatus:
		return new(RelayGetStatusResult)
	case MethodCreateTerminal:
		return new(CreateTerminalResult)
	case MethodWriteTerminalData:
		return new(WriteDataResult)
	case MethodResizeTerminal:
		return new(ResizeResult)
	case MethodCloseTerminal:
		return new(CloseTerminalResult)
	case MethodListTerminals:
		return new(ListTerminalsResult)
	case MethodListFiles:
		return new(ListFilesResult)
	case MethodSearchFiles:
		return new(SearchFilesResult)
	case MethodSearchSessions:
		return new(SearchSessionsResult)
	case MethodGetMCPConfig:
		return new(GetMCPConfigResult)
	case MethodUpdateMCPConfig:
		return new(UpdateMCPConfigResult)
	case MethodToggleMCPServer:
		return new(MCPSuccessResult)
	case MethodAuthenticateMCPServer:
		return new(MCPSuccessResult)
	case MethodClearMCPAuth:
		return new(MCPSuccessResult)
	case MethodCancelMCPAuth:
		return new(MCPSuccessResult)
	case MethodAddMCPServer:
		return new(MCPSuccessResult)
	case MethodRemoveMCPServer:
		return new(MCPSuccessResult)
	case MethodListMCPRegistry:
		return new(ListMCPRegistryResult)
	case MethodListMCPTools:
		return new(ListMCPToolsResult)
	case MethodListMCPServers:
		return new(ListMCPServersResult)
	case MethodToggleMCPTool:
		return new(MCPSuccessResult)
	case MethodSubmitMCPAuthCode:
		return new(MCPSuccessResult)
	case MethodSubmitMCPAuthError:
		return new(MCPSuccessResult)
	case MethodArchiveSession:
		return new(ArchiveSessionResult)
	case MethodUnarchiveSession:
		return new(UnarchiveSessionResult)
	case MethodRenameSession:
		return new(RenameSessionResult)
	case MethodListSkills:
		return new(ListSkillsResult)
	case MethodSetSkillDisabled:
		return new(SetSkillDisabledResult)
	case MethodListCommands:
		return new(ListCommandsResult)
	case MethodListAvailablePlugins:
		return new(ListAvailablePluginsResult)
	case MethodListInstalledPlugins:
		return new(ListInstalledPluginsResult)
	case MethodInstallPlugin:
		return new(InstallPluginResult)
	case MethodUninstallPlugin:
		return new(UninstallPluginResult)
	case MethodSetPluginEnabled:
		return new(SetPluginEnabledResult)
	case MethodUpdatePlugin:
		return new(UpdatePluginResult)
	case MethodListMarketplaces:
		return new(ListMarketplacesResult)
	case MethodAddMarketplace:
		return new(AddMarketplaceResult)
	case MethodRemoveMarketplace:
		return new(RemoveMarketplaceResult)
	case MethodUpdateMarketplace:
		return new(UpdateMarketplaceResult)
	case MethodSubmitBugReport:
		return new(SubmitBugReportResult)
	case MethodGetRewindInfo:
		return new(GetRewindInfoResult)
	case MethodExecuteRewind:
		return new(ExecuteRewindResult)
	case MethodCompactSession:
		return new(CompactSessionResult)
	case MethodForkSession:
		return new(ForkSessionResult)
	case MethodGetContextBreakdown:
		return new(GetContextBreakdownResult)
	case MethodListWorktreeSetupProfiles:
		return new(ListWorktreeSetupProfilesResult)
	case MethodSaveWorktreeSetupProfile:
		return new(SaveWorktreeSetupProfileResult)
	case MethodDeleteWorktreeSetupProfile:
		return new(DeleteWorktreeSetupProfileResult)
	case MethodListManagedWorktrees:
		return new(ListManagedWorktreesResult)
	case MethodCleanupWorktree:
		return new(CleanupWorktreeResult)
	case MethodInspectWorktreeDeletion:
		return new(InspectWorktreeDeletionResult)
	case MethodListAutomations:
		return new(ListAutomationsResult)
	case MethodRunAutomation:
		return new(RunAutomationResult)
	case MethodPauseAutomation:
		return new(PauseAutomationResult)
	case MethodResumeAutomation:
		return new(ResumeAutomationResult)
	case MethodGetAutomationHistory:
		return new(GetAutomationHistoryResult)
	case MethodGetAutomationVisual:
		return new(GetAutomationVisualResult)
	case MethodCreateAutomation:
		return new(CreateAutomationResult)
	case MethodUpdateAutomationModel:
		return new(UpdateAutomationModelResult)
	case MethodUpdateAutomationPrivacy:
		return new(UpdateAutomationPrivacyResult)
	case MethodUpdateAutomationPrompt:
		return new(UpdateAutomationPromptResult)
	case MethodUpdateAutomationSchedule:
		return new(UpdateAutomationScheduleResult)
	case MethodRenameAutomation:
		return new(RenameAutomationResult)
	case MethodDeleteAutomation:
		return new(DeleteAutomationResult)
	case MethodForkAutomation:
		return new(ForkAutomationResult)
	case MethodApplyAutomationConfig:
		return new(ApplyAutomationConfigResult)
	case MethodUpdateAutomation:
		return new(UpdateAutomationResult)
	case MethodSfListWorkstreams:
		return new(SfListWorkstreamsResult)
	case MethodSfGetWorkstream:
		return new(SfGetWorkstreamResult)
	case MethodSfCreateWorkstream:
		return new(SfCreateWorkstreamResult)
	case MethodSfUpdateWorkstream:
		return new(SfUpdateWorkstreamResult)
	case MethodSfDeleteWorkstream:
		return new(SfDeleteWorkstreamResult)
	case MethodSfPublishWorkstreamContent:
		return new(SfPublishWorkstreamContentResult)
	case MethodSfHydrateWorkstreamContent:
		return new(SfHydrateWorkstreamContentResult)
	case MethodSfListSignals:
		return new(SfListSignalsResult)
	case MethodSfListChanges:
		return new(SfListChangesResult)
	case MethodSfListActivities:
		return new(SfListActivitiesResult)
	case MethodSfResolveActivityReview:
		return new(SfResolveActivityReviewResult)
	case MethodSfListEvents:
		return new(SfListEventsResult)
	case MethodSfMarkEventsRead:
		return new(SfMarkEventsReadResult)
	case MethodSfMarkEventsUnread:
		return new(SfMarkEventsUnreadResult)
	case MethodListCrons:
		return new(ListCronsResult)
	case MethodCreateCron:
		return new(CreateCronResult)
	case MethodUpdateCron:
		return new(UpdateCronResult)
	case MethodDeleteCron:
		return new(DeleteCronResult)
	case MethodHoldSessionCrons:
		return new(HoldSessionCronsResult)
	case MethodResumeSessionCrons:
		return new(ResumeSessionCronsResult)
	case MethodGetGitDiff:
		return new(GetGitDiffResult)
	case MethodListGitBranches:
		return new(ListGitBranchesResult)
	case MethodCheckoutGitBranch:
		return new(DaemonCheckoutGitBranchResult)
	case MethodResolvePullRequestStatuses:
		return new(ResolvePullRequestStatusesResult)
	case MethodGetGitBranchDivergence:
		return new(DaemonGetGitBranchDivergenceResult)
	case MethodInspectMissionReadiness:
		return new(InspectMissionReadinessResult)
	case MethodAcknowledgeMissionReadinessWarning:
		return new(AcknowledgeMissionReadinessWarningResult)
	case MethodGitPush:
		return new(GitPushResult)
	case MethodGitCommit:
		return new(GitCommitResult)
	case MethodCreatePR:
		return new(CreatePRResult)
	case MethodGetSemanticDiffCache:
		return new(GetSemanticDiffCacheResult)
	case MethodSaveSemanticDiffCache:
		return new(SaveSemanticDiffCacheResult)
	case MethodGenerateSemanticDiff:
		return new(GenerateSemanticDiffResult)
	case MethodGetProxyToken:
		return new(GetProxyTokenResult)
	case MethodGetWorkspaceFileContent:
		return new(GetWorkspaceFileContentResult)
	case MethodWriteWorkspaceFileContent:
		return new(WriteWorkspaceFileContentResult)
	case MethodPushCwdFileToURL:
		return new(PushCwdFileToURLResult)
	case MethodPullURLToCwdFile:
		return new(PullURLToCwdFileResult)
	}
	return nil
}

// Methods describes every method in the table above.
var Methods = map[string]MethodInfo{
	"daemon.authenticate":                          {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.logout":                                {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.initialize_session":                    {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.load_session":                          {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.add_user_message":                      {Ack: true, CompletedBy: "create_message", Timeout: 0},
	"daemon.resolve_queued_user_message":           {Ack: true, CompletedBy: "create_message", Timeout: 0},
	"daemon.interrupt_session":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.close_session":                         {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.kill_worker_session":                   {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_opened_sessions":                  {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_available_sessions":               {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_models":                           {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_session_messages":                  {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_session_settings":               {Ack: true, CompletedBy: "settings_updated", Timeout: 0},
	"daemon.change_working_directory":              {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.validate_working_directory":            {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.check_folder_trust":                    {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.trust_folder":                          {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_default_settings":                  {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_session_defaults":               {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_custom_models":                    {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.upsert_custom_model":                   {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.delete_custom_model":                   {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.trigger_update":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.install_ssh_key":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.relay.start":                           {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.relay.stop":                            {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.relay.get_status":                      {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.create_terminal":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.write_terminal_data":                   {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.resize_terminal":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.close_terminal":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_terminals":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_files":                            {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.search_files":                          {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.search_sessions":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_mcp_config":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_mcp_config":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.toggle_mcp_server":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.authenticate_mcp_server":               {Ack: false, CompletedBy: "", Timeout: 300 * time.Second},
	"daemon.clear_mcp_auth":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.cancel_mcp_auth":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.add_mcp_server":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.remove_mcp_server":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_mcp_registry":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_mcp_tools":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_mcp_servers":                      {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.toggle_mcp_tool":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.submit_mcp_auth_code":                  {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.submit_mcp_auth_error":                 {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.archive_session":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.unarchive_session":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.rename_session":                        {Ack: true, CompletedBy: "session_title_updated", Timeout: 0},
	"daemon.list_skills":                           {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.set_skill_disabled":                    {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_commands":                         {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_available_plugins":                {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_installed_plugins":                {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.install_plugin":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.uninstall_plugin":                      {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.set_plugin_enabled":                    {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_plugin":                         {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_marketplaces":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.add_marketplace":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.remove_marketplace":                    {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_marketplace":                    {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.submit_bug_report":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_rewind_info":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.execute_rewind":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.compact_session":                       {Ack: false, CompletedBy: "", Timeout: 240 * time.Second},
	"daemon.fork_session":                          {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_context_breakdown":                 {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_worktree_setup_profiles":          {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.save_worktree_setup_profile":           {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.delete_worktree_setup_profile":         {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_managed_worktrees":                {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.cleanup_worktree":                      {Ack: false, CompletedBy: "", Timeout: 180 * time.Second},
	"daemon.inspect_worktree_deletion":             {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_automations":                      {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.run_automation":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.pause_automation":                      {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.resume_automation":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_automation_history":                {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_automation_visual":                 {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.create_automation":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_automation_model":               {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_automation_privacy":             {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_automation_prompt":              {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_automation_schedule":            {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.rename_automation":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.delete_automation":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.fork_automation":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.apply_automation_config":               {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_automation":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.list_workstreams":                   {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.get_workstream":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.create_workstream":                  {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.update_workstream":                  {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.delete_workstream":                  {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.publish_workstream_content":         {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.hydrate_workstream_content":         {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.list_signals":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.list_changes":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.list_activities":                    {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.resolve_activity_review":            {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.list_events":                        {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.mark_events_read":                   {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.sf.mark_events_unread":                 {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_crons":                            {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.create_cron":                           {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.update_cron":                           {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.delete_cron":                           {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.hold_session_crons":                    {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.resume_session_crons":                  {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_git_diff":                          {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.list_git_branches":                     {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.checkout_git_branch":                   {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.resolve_pull_request_statuses":         {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_git_branch_divergence":             {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.inspect_mission_readiness":             {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.acknowledge_mission_readiness_warning": {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.git_push":                              {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.git_commit":                            {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.create_pr":                             {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_semantic_diff_cache":               {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.save_semantic_diff_cache":              {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.generate_semantic_diff":                {Ack: false, CompletedBy: "", Timeout: 180 * time.Second},
	"daemon.get_proxy_token":                       {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.get_workspace_file_content":            {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.write_workspace_file_content":          {Ack: false, CompletedBy: "", Timeout: 0},
	"daemon.push_cwd_file_to_url":                  {Ack: false, CompletedBy: "", Timeout: 900 * time.Second},
	"daemon.pull_url_to_cwd_file":                  {Ack: false, CompletedBy: "", Timeout: 900 * time.Second},
}
