// Code generated by gen/gen.mjs from @factory/droid-sdk 0.9.1. DO NOT EDIT.

package droid

import (
	"context"
	"encoding/json"

	"github.com/kkkk2323/droi/packages/droid-sdk-go/protocol"
)

// Authenticate calls daemon.authenticate.
func (c *Client) Authenticate(ctx context.Context, params protocol.AuthenticateParams) (*protocol.AuthenticateResult, error) {
	var out protocol.AuthenticateResult
	return &out, c.Call(ctx, protocol.MethodAuthenticate, params, &out)
}

// Logout calls daemon.logout.
func (c *Client) Logout(ctx context.Context) (*protocol.LogoutResult, error) {
	var out protocol.LogoutResult
	return &out, c.Call(ctx, protocol.MethodLogout, struct{}{}, &out)
}

// InitializeSession calls daemon.initialize_session.
func (c *Client) InitializeSession(ctx context.Context, params protocol.InitializeSessionParams) (*protocol.InitializeSessionResult, error) {
	var out protocol.InitializeSessionResult
	return &out, c.Call(ctx, protocol.MethodInitializeSession, params, &out)
}

// LoadSession calls daemon.load_session.
func (c *Client) LoadSession(ctx context.Context, params protocol.LoadSessionParams) (*protocol.LoadSessionResult, error) {
	var out protocol.LoadSessionResult
	return &out, c.Call(ctx, protocol.MethodLoadSession, params, &out)
}

// AddUserMessage calls daemon.add_user_message.
func (c *Client) AddUserMessage(ctx context.Context, params protocol.AddUserMessageParams) (*protocol.AddUserMessageResult, error) {
	var out protocol.AddUserMessageResult
	return &out, c.Call(ctx, protocol.MethodAddUserMessage, params, &out)
}

// ResolveQueuedUserMessage calls daemon.resolve_queued_user_message.
func (c *Client) ResolveQueuedUserMessage(ctx context.Context, params json.RawMessage) (*protocol.ResolveQueuedUserMessageResult, error) {
	var out protocol.ResolveQueuedUserMessageResult
	return &out, c.Call(ctx, protocol.MethodResolveQueuedUserMessage, params, &out)
}

// InterruptSession calls daemon.interrupt_session.
func (c *Client) InterruptSession(ctx context.Context, params protocol.InterruptSessionParams) (*protocol.InterruptSessionResult, error) {
	var out protocol.InterruptSessionResult
	return &out, c.Call(ctx, protocol.MethodInterruptSession, params, &out)
}

// CloseSession calls daemon.close_session.
func (c *Client) CloseSession(ctx context.Context, params protocol.CloseSessionParams) (*protocol.CloseSessionResult, error) {
	var out protocol.CloseSessionResult
	return &out, c.Call(ctx, protocol.MethodCloseSession, params, &out)
}

// KillWorkerSession calls daemon.kill_worker_session.
func (c *Client) KillWorkerSession(ctx context.Context, params protocol.KillWorkerSessionParams) (*protocol.KillWorkerSessionResult, error) {
	var out protocol.KillWorkerSessionResult
	return &out, c.Call(ctx, protocol.MethodKillWorkerSession, params, &out)
}

// ListOpenedSessions calls daemon.list_opened_sessions.
func (c *Client) ListOpenedSessions(ctx context.Context, params protocol.ListOpenedSessionsParams) (*protocol.ListOpenedSessionsResult, error) {
	var out protocol.ListOpenedSessionsResult
	return &out, c.Call(ctx, protocol.MethodListOpenedSessions, params, &out)
}

// ListAvailableSessions calls daemon.list_available_sessions.
func (c *Client) ListAvailableSessions(ctx context.Context, params protocol.ListAvailableSessionsParams) (*protocol.ListAvailableSessionsResult, error) {
	var out protocol.ListAvailableSessionsResult
	return &out, c.Call(ctx, protocol.MethodListAvailableSessions, params, &out)
}

// ListModels calls daemon.list_models.
func (c *Client) ListModels(ctx context.Context, params protocol.ListModelsParams) (*protocol.ListModelsResult, error) {
	var out protocol.ListModelsResult
	return &out, c.Call(ctx, protocol.MethodListModels, params, &out)
}

// GetSessionMessages calls daemon.get_session_messages.
func (c *Client) GetSessionMessages(ctx context.Context, params protocol.GetSessionMessagesParams) (*protocol.GetSessionMessagesResult, error) {
	var out protocol.GetSessionMessagesResult
	return &out, c.Call(ctx, protocol.MethodGetSessionMessages, params, &out)
}

// UpdateSessionSettings calls daemon.update_session_settings.
func (c *Client) UpdateSessionSettings(ctx context.Context, params protocol.UpdateSessionSettingsParams) (*protocol.UpdateSessionSettingsResult, error) {
	var out protocol.UpdateSessionSettingsResult
	return &out, c.Call(ctx, protocol.MethodUpdateSessionSettings, params, &out)
}

// ChangeWorkingDirectory calls daemon.change_working_directory.
func (c *Client) ChangeWorkingDirectory(ctx context.Context, params protocol.ChangeWorkingDirectoryParams) (*protocol.ChangeWorkingDirectoryResult, error) {
	var out protocol.ChangeWorkingDirectoryResult
	return &out, c.Call(ctx, protocol.MethodChangeWorkingDirectory, params, &out)
}

// ValidateWorkingDirectory calls daemon.validate_working_directory.
func (c *Client) ValidateWorkingDirectory(ctx context.Context, params protocol.ValidateWorkingDirectoryParams) (*protocol.ValidateWorkingDirectoryResult, error) {
	var out protocol.ValidateWorkingDirectoryResult
	return &out, c.Call(ctx, protocol.MethodValidateWorkingDirectory, params, &out)
}

// CheckFolderTrust calls daemon.check_folder_trust.
func (c *Client) CheckFolderTrust(ctx context.Context, params protocol.CheckFolderTrustParams) (*protocol.CheckFolderTrustResult, error) {
	var out protocol.CheckFolderTrustResult
	return &out, c.Call(ctx, protocol.MethodCheckFolderTrust, params, &out)
}

// TrustFolder calls daemon.trust_folder.
func (c *Client) TrustFolder(ctx context.Context, params protocol.TrustFolderParams) (*protocol.TrustFolderResult, error) {
	var out protocol.TrustFolderResult
	return &out, c.Call(ctx, protocol.MethodTrustFolder, params, &out)
}

// GetDefaultSettings calls daemon.get_default_settings.
func (c *Client) GetDefaultSettings(ctx context.Context) (*protocol.GetDefaultSettingsResult, error) {
	var out protocol.GetDefaultSettingsResult
	return &out, c.Call(ctx, protocol.MethodGetDefaultSettings, struct{}{}, &out)
}

// UpdateSessionDefaults calls daemon.update_session_defaults.
func (c *Client) UpdateSessionDefaults(ctx context.Context, params protocol.UpdateSessionDefaultsParams) (*protocol.UpdateSessionDefaultsResult, error) {
	var out protocol.UpdateSessionDefaultsResult
	return &out, c.Call(ctx, protocol.MethodUpdateSessionDefaults, params, &out)
}

// ListCustomModels calls daemon.list_custom_models.
func (c *Client) ListCustomModels(ctx context.Context) (*protocol.ListCustomModelsResult, error) {
	var out protocol.ListCustomModelsResult
	return &out, c.Call(ctx, protocol.MethodListCustomModels, struct{}{}, &out)
}

// UpsertCustomModel calls daemon.upsert_custom_model.
func (c *Client) UpsertCustomModel(ctx context.Context, params protocol.UpsertCustomModelParams) (*protocol.UpsertCustomModelResult, error) {
	var out protocol.UpsertCustomModelResult
	return &out, c.Call(ctx, protocol.MethodUpsertCustomModel, params, &out)
}

// DeleteCustomModel calls daemon.delete_custom_model.
func (c *Client) DeleteCustomModel(ctx context.Context, params protocol.DeleteCustomModelParams) (*protocol.DeleteCustomModelResult, error) {
	var out protocol.DeleteCustomModelResult
	return &out, c.Call(ctx, protocol.MethodDeleteCustomModel, params, &out)
}

// TriggerUpdate calls daemon.trigger_update.
func (c *Client) TriggerUpdate(ctx context.Context) (*protocol.TriggerUpdateResult, error) {
	var out protocol.TriggerUpdateResult
	return &out, c.Call(ctx, protocol.MethodTriggerUpdate, struct{}{}, &out)
}

// InstallSSHKey calls daemon.install_ssh_key.
func (c *Client) InstallSSHKey(ctx context.Context, params protocol.InstallSSHKeyParams) (*protocol.InstallSSHKeyResult, error) {
	var out protocol.InstallSSHKeyResult
	return &out, c.Call(ctx, protocol.MethodInstallSSHKey, params, &out)
}

// RelayStart calls daemon.relay.start.
func (c *Client) RelayStart(ctx context.Context) (*protocol.RelayStartResult, error) {
	var out protocol.RelayStartResult
	return &out, c.Call(ctx, protocol.MethodRelayStart, struct{}{}, &out)
}

// RelayStop calls daemon.relay.stop.
func (c *Client) RelayStop(ctx context.Context) (*protocol.RelayStopResult, error) {
	var out protocol.RelayStopResult
	return &out, c.Call(ctx, protocol.MethodRelayStop, struct{}{}, &out)
}

// RelayGetStatus calls daemon.relay.get_status.
func (c *Client) RelayGetStatus(ctx context.Context) (*protocol.RelayGetStatusResult, error) {
	var out protocol.RelayGetStatusResult
	return &out, c.Call(ctx, protocol.MethodRelayGetStatus, struct{}{}, &out)
}

// CreateTerminal calls daemon.create_terminal.
func (c *Client) CreateTerminal(ctx context.Context, params protocol.CreateTerminalParams) (*protocol.CreateTerminalResult, error) {
	var out protocol.CreateTerminalResult
	return &out, c.Call(ctx, protocol.MethodCreateTerminal, params, &out)
}

// WriteTerminalData calls daemon.write_terminal_data.
func (c *Client) WriteTerminalData(ctx context.Context, params protocol.WriteTerminalDataParams) (*protocol.WriteDataResult, error) {
	var out protocol.WriteDataResult
	return &out, c.Call(ctx, protocol.MethodWriteTerminalData, params, &out)
}

// ResizeTerminal calls daemon.resize_terminal.
func (c *Client) ResizeTerminal(ctx context.Context, params protocol.ResizeTerminalParams) (*protocol.ResizeResult, error) {
	var out protocol.ResizeResult
	return &out, c.Call(ctx, protocol.MethodResizeTerminal, params, &out)
}

// CloseTerminal calls daemon.close_terminal.
func (c *Client) CloseTerminal(ctx context.Context, params protocol.CloseTerminalParams) (*protocol.CloseTerminalResult, error) {
	var out protocol.CloseTerminalResult
	return &out, c.Call(ctx, protocol.MethodCloseTerminal, params, &out)
}

// ListTerminals calls daemon.list_terminals.
func (c *Client) ListTerminals(ctx context.Context, params protocol.ListTerminalsParams) (*protocol.ListTerminalsResult, error) {
	var out protocol.ListTerminalsResult
	return &out, c.Call(ctx, protocol.MethodListTerminals, params, &out)
}

// ListFiles calls daemon.list_files.
func (c *Client) ListFiles(ctx context.Context, params protocol.ListFilesParams) (*protocol.ListFilesResult, error) {
	var out protocol.ListFilesResult
	return &out, c.Call(ctx, protocol.MethodListFiles, params, &out)
}

// SearchFiles calls daemon.search_files.
func (c *Client) SearchFiles(ctx context.Context, params protocol.SearchFilesParams) (*protocol.SearchFilesResult, error) {
	var out protocol.SearchFilesResult
	return &out, c.Call(ctx, protocol.MethodSearchFiles, params, &out)
}

// SearchSessions calls daemon.search_sessions.
func (c *Client) SearchSessions(ctx context.Context, params protocol.SearchSessionsParams) (*protocol.SearchSessionsResult, error) {
	var out protocol.SearchSessionsResult
	return &out, c.Call(ctx, protocol.MethodSearchSessions, params, &out)
}

// GetMCPConfig calls daemon.get_mcp_config.
func (c *Client) GetMCPConfig(ctx context.Context) (*protocol.GetMCPConfigResult, error) {
	var out protocol.GetMCPConfigResult
	return &out, c.Call(ctx, protocol.MethodGetMCPConfig, struct{}{}, &out)
}

// UpdateMCPConfig calls daemon.update_mcp_config.
func (c *Client) UpdateMCPConfig(ctx context.Context, params protocol.UpdateMCPConfigParams) (*protocol.UpdateMCPConfigResult, error) {
	var out protocol.UpdateMCPConfigResult
	return &out, c.Call(ctx, protocol.MethodUpdateMCPConfig, params, &out)
}

// ToggleMCPServer calls daemon.toggle_mcp_server.
func (c *Client) ToggleMCPServer(ctx context.Context, params protocol.ToggleMCPServerParams) (*protocol.MCPSuccessResult, error) {
	var out protocol.MCPSuccessResult
	return &out, c.Call(ctx, protocol.MethodToggleMCPServer, params, &out)
}

// AuthenticateMCPServer calls daemon.authenticate_mcp_server.
func (c *Client) AuthenticateMCPServer(ctx context.Context, params protocol.AuthenticateMCPServerParams) (*protocol.MCPSuccessResult, error) {
	var out protocol.MCPSuccessResult
	return &out, c.Call(ctx, protocol.MethodAuthenticateMCPServer, params, &out)
}

// ClearMCPAuth calls daemon.clear_mcp_auth.
func (c *Client) ClearMCPAuth(ctx context.Context, params protocol.ClearMCPAuthParams) (*protocol.MCPSuccessResult, error) {
	var out protocol.MCPSuccessResult
	return &out, c.Call(ctx, protocol.MethodClearMCPAuth, params, &out)
}

// CancelMCPAuth calls daemon.cancel_mcp_auth.
func (c *Client) CancelMCPAuth(ctx context.Context, params protocol.CancelMCPAuthParams) (*protocol.MCPSuccessResult, error) {
	var out protocol.MCPSuccessResult
	return &out, c.Call(ctx, protocol.MethodCancelMCPAuth, params, &out)
}

// AddMCPServer calls daemon.add_mcp_server.
func (c *Client) AddMCPServer(ctx context.Context, params protocol.AddMCPServerParams) (*protocol.MCPSuccessResult, error) {
	var out protocol.MCPSuccessResult
	return &out, c.Call(ctx, protocol.MethodAddMCPServer, params, &out)
}

// RemoveMCPServer calls daemon.remove_mcp_server.
func (c *Client) RemoveMCPServer(ctx context.Context, params protocol.RemoveMCPServerParams) (*protocol.MCPSuccessResult, error) {
	var out protocol.MCPSuccessResult
	return &out, c.Call(ctx, protocol.MethodRemoveMCPServer, params, &out)
}

// ListMCPRegistry calls daemon.list_mcp_registry.
func (c *Client) ListMCPRegistry(ctx context.Context, params protocol.ListMCPRegistryParams) (*protocol.ListMCPRegistryResult, error) {
	var out protocol.ListMCPRegistryResult
	return &out, c.Call(ctx, protocol.MethodListMCPRegistry, params, &out)
}

// ListMCPTools calls daemon.list_mcp_tools.
func (c *Client) ListMCPTools(ctx context.Context, params protocol.ListMCPToolsParams) (*protocol.ListMCPToolsResult, error) {
	var out protocol.ListMCPToolsResult
	return &out, c.Call(ctx, protocol.MethodListMCPTools, params, &out)
}

// ListMCPServers calls daemon.list_mcp_servers.
func (c *Client) ListMCPServers(ctx context.Context, params protocol.ListMCPServersParams) (*protocol.ListMCPServersResult, error) {
	var out protocol.ListMCPServersResult
	return &out, c.Call(ctx, protocol.MethodListMCPServers, params, &out)
}

// ToggleMCPTool calls daemon.toggle_mcp_tool.
func (c *Client) ToggleMCPTool(ctx context.Context, params protocol.ToggleMCPToolParams) (*protocol.MCPSuccessResult, error) {
	var out protocol.MCPSuccessResult
	return &out, c.Call(ctx, protocol.MethodToggleMCPTool, params, &out)
}

// SubmitMCPAuthCode calls daemon.submit_mcp_auth_code.
func (c *Client) SubmitMCPAuthCode(ctx context.Context, params protocol.SubmitMCPAuthCodeParams) (*protocol.MCPSuccessResult, error) {
	var out protocol.MCPSuccessResult
	return &out, c.Call(ctx, protocol.MethodSubmitMCPAuthCode, params, &out)
}

// SubmitMCPAuthError calls daemon.submit_mcp_auth_error.
func (c *Client) SubmitMCPAuthError(ctx context.Context, params protocol.SubmitMCPAuthErrorParams) (*protocol.MCPSuccessResult, error) {
	var out protocol.MCPSuccessResult
	return &out, c.Call(ctx, protocol.MethodSubmitMCPAuthError, params, &out)
}

// ArchiveSession calls daemon.archive_session.
func (c *Client) ArchiveSession(ctx context.Context, params protocol.ArchiveSessionParams) (*protocol.ArchiveSessionResult, error) {
	var out protocol.ArchiveSessionResult
	return &out, c.Call(ctx, protocol.MethodArchiveSession, params, &out)
}

// UnarchiveSession calls daemon.unarchive_session.
func (c *Client) UnarchiveSession(ctx context.Context, params protocol.UnarchiveSessionParams) (*protocol.UnarchiveSessionResult, error) {
	var out protocol.UnarchiveSessionResult
	return &out, c.Call(ctx, protocol.MethodUnarchiveSession, params, &out)
}

// RenameSession calls daemon.rename_session.
func (c *Client) RenameSession(ctx context.Context, params protocol.RenameSessionParams) (*protocol.RenameSessionResult, error) {
	var out protocol.RenameSessionResult
	return &out, c.Call(ctx, protocol.MethodRenameSession, params, &out)
}

// ListSkills calls daemon.list_skills.
func (c *Client) ListSkills(ctx context.Context, params protocol.ListSkillsParams) (*protocol.ListSkillsResult, error) {
	var out protocol.ListSkillsResult
	return &out, c.Call(ctx, protocol.MethodListSkills, params, &out)
}

// SetSkillDisabled calls daemon.set_skill_disabled.
func (c *Client) SetSkillDisabled(ctx context.Context, params protocol.SetSkillDisabledParams) (*protocol.SetSkillDisabledResult, error) {
	var out protocol.SetSkillDisabledResult
	return &out, c.Call(ctx, protocol.MethodSetSkillDisabled, params, &out)
}

// ListCommands calls daemon.list_commands.
func (c *Client) ListCommands(ctx context.Context, params protocol.ListCommandsParams) (*protocol.ListCommandsResult, error) {
	var out protocol.ListCommandsResult
	return &out, c.Call(ctx, protocol.MethodListCommands, params, &out)
}

// ListAvailablePlugins calls daemon.list_available_plugins.
func (c *Client) ListAvailablePlugins(ctx context.Context, params protocol.ListAvailablePluginsParams) (*protocol.ListAvailablePluginsResult, error) {
	var out protocol.ListAvailablePluginsResult
	return &out, c.Call(ctx, protocol.MethodListAvailablePlugins, params, &out)
}

// ListInstalledPlugins calls daemon.list_installed_plugins.
func (c *Client) ListInstalledPlugins(ctx context.Context, params protocol.ListInstalledPluginsParams) (*protocol.ListInstalledPluginsResult, error) {
	var out protocol.ListInstalledPluginsResult
	return &out, c.Call(ctx, protocol.MethodListInstalledPlugins, params, &out)
}

// InstallPlugin calls daemon.install_plugin.
func (c *Client) InstallPlugin(ctx context.Context, params protocol.InstallPluginParams) (*protocol.InstallPluginResult, error) {
	var out protocol.InstallPluginResult
	return &out, c.Call(ctx, protocol.MethodInstallPlugin, params, &out)
}

// UninstallPlugin calls daemon.uninstall_plugin.
func (c *Client) UninstallPlugin(ctx context.Context, params protocol.UninstallPluginParams) (*protocol.UninstallPluginResult, error) {
	var out protocol.UninstallPluginResult
	return &out, c.Call(ctx, protocol.MethodUninstallPlugin, params, &out)
}

// SetPluginEnabled calls daemon.set_plugin_enabled.
func (c *Client) SetPluginEnabled(ctx context.Context, params protocol.SetPluginEnabledParams) (*protocol.SetPluginEnabledResult, error) {
	var out protocol.SetPluginEnabledResult
	return &out, c.Call(ctx, protocol.MethodSetPluginEnabled, params, &out)
}

// UpdatePlugin calls daemon.update_plugin.
func (c *Client) UpdatePlugin(ctx context.Context, params protocol.UpdatePluginParams) (*protocol.UpdatePluginResult, error) {
	var out protocol.UpdatePluginResult
	return &out, c.Call(ctx, protocol.MethodUpdatePlugin, params, &out)
}

// ListMarketplaces calls daemon.list_marketplaces.
func (c *Client) ListMarketplaces(ctx context.Context, params protocol.ListMarketplacesParams) (*protocol.ListMarketplacesResult, error) {
	var out protocol.ListMarketplacesResult
	return &out, c.Call(ctx, protocol.MethodListMarketplaces, params, &out)
}

// AddMarketplace calls daemon.add_marketplace.
func (c *Client) AddMarketplace(ctx context.Context, params protocol.AddMarketplaceParams) (*protocol.AddMarketplaceResult, error) {
	var out protocol.AddMarketplaceResult
	return &out, c.Call(ctx, protocol.MethodAddMarketplace, params, &out)
}

// RemoveMarketplace calls daemon.remove_marketplace.
func (c *Client) RemoveMarketplace(ctx context.Context, params protocol.RemoveMarketplaceParams) (*protocol.RemoveMarketplaceResult, error) {
	var out protocol.RemoveMarketplaceResult
	return &out, c.Call(ctx, protocol.MethodRemoveMarketplace, params, &out)
}

// UpdateMarketplace calls daemon.update_marketplace.
func (c *Client) UpdateMarketplace(ctx context.Context, params protocol.UpdateMarketplaceParams) (*protocol.UpdateMarketplaceResult, error) {
	var out protocol.UpdateMarketplaceResult
	return &out, c.Call(ctx, protocol.MethodUpdateMarketplace, params, &out)
}

// SubmitBugReport calls daemon.submit_bug_report.
func (c *Client) SubmitBugReport(ctx context.Context, params protocol.SubmitBugReportParams) (*protocol.SubmitBugReportResult, error) {
	var out protocol.SubmitBugReportResult
	return &out, c.Call(ctx, protocol.MethodSubmitBugReport, params, &out)
}

// GetRewindInfo calls daemon.get_rewind_info.
func (c *Client) GetRewindInfo(ctx context.Context, params protocol.GetRewindInfoParams) (*protocol.GetRewindInfoResult, error) {
	var out protocol.GetRewindInfoResult
	return &out, c.Call(ctx, protocol.MethodGetRewindInfo, params, &out)
}

// ExecuteRewind calls daemon.execute_rewind.
func (c *Client) ExecuteRewind(ctx context.Context, params protocol.ExecuteRewindParams) (*protocol.ExecuteRewindResult, error) {
	var out protocol.ExecuteRewindResult
	return &out, c.Call(ctx, protocol.MethodExecuteRewind, params, &out)
}

// CompactSession calls daemon.compact_session.
func (c *Client) CompactSession(ctx context.Context, params protocol.CompactSessionParams) (*protocol.CompactSessionResult, error) {
	var out protocol.CompactSessionResult
	return &out, c.Call(ctx, protocol.MethodCompactSession, params, &out)
}

// ForkSession calls daemon.fork_session.
func (c *Client) ForkSession(ctx context.Context, params protocol.ForkSessionParams) (*protocol.ForkSessionResult, error) {
	var out protocol.ForkSessionResult
	return &out, c.Call(ctx, protocol.MethodForkSession, params, &out)
}

// GetContextBreakdown calls daemon.get_context_breakdown.
func (c *Client) GetContextBreakdown(ctx context.Context, params protocol.GetContextBreakdownParams) (*protocol.GetContextBreakdownResult, error) {
	var out protocol.GetContextBreakdownResult
	return &out, c.Call(ctx, protocol.MethodGetContextBreakdown, params, &out)
}

// ListWorktreeSetupProfiles calls daemon.list_worktree_setup_profiles.
func (c *Client) ListWorktreeSetupProfiles(ctx context.Context, params protocol.ListWorktreeSetupProfilesParams) (*protocol.ListWorktreeSetupProfilesResult, error) {
	var out protocol.ListWorktreeSetupProfilesResult
	return &out, c.Call(ctx, protocol.MethodListWorktreeSetupProfiles, params, &out)
}

// SaveWorktreeSetupProfile calls daemon.save_worktree_setup_profile.
func (c *Client) SaveWorktreeSetupProfile(ctx context.Context, params protocol.SaveWorktreeSetupProfileParams) (*protocol.SaveWorktreeSetupProfileResult, error) {
	var out protocol.SaveWorktreeSetupProfileResult
	return &out, c.Call(ctx, protocol.MethodSaveWorktreeSetupProfile, params, &out)
}

// DeleteWorktreeSetupProfile calls daemon.delete_worktree_setup_profile.
func (c *Client) DeleteWorktreeSetupProfile(ctx context.Context, params protocol.DeleteWorktreeSetupProfileParams) (*protocol.DeleteWorktreeSetupProfileResult, error) {
	var out protocol.DeleteWorktreeSetupProfileResult
	return &out, c.Call(ctx, protocol.MethodDeleteWorktreeSetupProfile, params, &out)
}

// ListManagedWorktrees calls daemon.list_managed_worktrees.
func (c *Client) ListManagedWorktrees(ctx context.Context, params protocol.ListManagedWorktreesParams) (*protocol.ListManagedWorktreesResult, error) {
	var out protocol.ListManagedWorktreesResult
	return &out, c.Call(ctx, protocol.MethodListManagedWorktrees, params, &out)
}

// CleanupWorktree calls daemon.cleanup_worktree.
func (c *Client) CleanupWorktree(ctx context.Context, params protocol.CleanupWorktreeParams) (*protocol.CleanupWorktreeResult, error) {
	var out protocol.CleanupWorktreeResult
	return &out, c.Call(ctx, protocol.MethodCleanupWorktree, params, &out)
}

// InspectWorktreeDeletion calls daemon.inspect_worktree_deletion.
func (c *Client) InspectWorktreeDeletion(ctx context.Context, params protocol.InspectWorktreeDeletionParams) (*protocol.InspectWorktreeDeletionResult, error) {
	var out protocol.InspectWorktreeDeletionResult
	return &out, c.Call(ctx, protocol.MethodInspectWorktreeDeletion, params, &out)
}

// ListAutomations calls daemon.list_automations.
func (c *Client) ListAutomations(ctx context.Context, params protocol.ListAutomationsParams) (*protocol.ListAutomationsResult, error) {
	var out protocol.ListAutomationsResult
	return &out, c.Call(ctx, protocol.MethodListAutomations, params, &out)
}

// RunAutomation calls daemon.run_automation.
func (c *Client) RunAutomation(ctx context.Context, params protocol.RunAutomationParams) (*protocol.RunAutomationResult, error) {
	var out protocol.RunAutomationResult
	return &out, c.Call(ctx, protocol.MethodRunAutomation, params, &out)
}

// PauseAutomation calls daemon.pause_automation.
func (c *Client) PauseAutomation(ctx context.Context, params protocol.PauseAutomationParams) (*protocol.PauseAutomationResult, error) {
	var out protocol.PauseAutomationResult
	return &out, c.Call(ctx, protocol.MethodPauseAutomation, params, &out)
}

// ResumeAutomation calls daemon.resume_automation.
func (c *Client) ResumeAutomation(ctx context.Context, params protocol.ResumeAutomationParams) (*protocol.ResumeAutomationResult, error) {
	var out protocol.ResumeAutomationResult
	return &out, c.Call(ctx, protocol.MethodResumeAutomation, params, &out)
}

// GetAutomationHistory calls daemon.get_automation_history.
func (c *Client) GetAutomationHistory(ctx context.Context, params protocol.GetAutomationHistoryParams) (*protocol.GetAutomationHistoryResult, error) {
	var out protocol.GetAutomationHistoryResult
	return &out, c.Call(ctx, protocol.MethodGetAutomationHistory, params, &out)
}

// GetAutomationVisual calls daemon.get_automation_visual.
func (c *Client) GetAutomationVisual(ctx context.Context, params protocol.GetAutomationVisualParams) (*protocol.GetAutomationVisualResult, error) {
	var out protocol.GetAutomationVisualResult
	return &out, c.Call(ctx, protocol.MethodGetAutomationVisual, params, &out)
}

// CreateAutomation calls daemon.create_automation.
func (c *Client) CreateAutomation(ctx context.Context, params protocol.CreateAutomationParams) (*protocol.CreateAutomationResult, error) {
	var out protocol.CreateAutomationResult
	return &out, c.Call(ctx, protocol.MethodCreateAutomation, params, &out)
}

// UpdateAutomationModel calls daemon.update_automation_model.
func (c *Client) UpdateAutomationModel(ctx context.Context, params protocol.UpdateAutomationModelParams) (*protocol.UpdateAutomationModelResult, error) {
	var out protocol.UpdateAutomationModelResult
	return &out, c.Call(ctx, protocol.MethodUpdateAutomationModel, params, &out)
}

// UpdateAutomationPrivacy calls daemon.update_automation_privacy.
func (c *Client) UpdateAutomationPrivacy(ctx context.Context, params protocol.UpdateAutomationPrivacyParams) (*protocol.UpdateAutomationPrivacyResult, error) {
	var out protocol.UpdateAutomationPrivacyResult
	return &out, c.Call(ctx, protocol.MethodUpdateAutomationPrivacy, params, &out)
}

// UpdateAutomationPrompt calls daemon.update_automation_prompt.
func (c *Client) UpdateAutomationPrompt(ctx context.Context, params protocol.UpdateAutomationPromptParams) (*protocol.UpdateAutomationPromptResult, error) {
	var out protocol.UpdateAutomationPromptResult
	return &out, c.Call(ctx, protocol.MethodUpdateAutomationPrompt, params, &out)
}

// UpdateAutomationSchedule calls daemon.update_automation_schedule.
func (c *Client) UpdateAutomationSchedule(ctx context.Context, params protocol.UpdateAutomationScheduleParams) (*protocol.UpdateAutomationScheduleResult, error) {
	var out protocol.UpdateAutomationScheduleResult
	return &out, c.Call(ctx, protocol.MethodUpdateAutomationSchedule, params, &out)
}

// RenameAutomation calls daemon.rename_automation.
func (c *Client) RenameAutomation(ctx context.Context, params protocol.RenameAutomationParams) (*protocol.RenameAutomationResult, error) {
	var out protocol.RenameAutomationResult
	return &out, c.Call(ctx, protocol.MethodRenameAutomation, params, &out)
}

// DeleteAutomation calls daemon.delete_automation.
func (c *Client) DeleteAutomation(ctx context.Context, params protocol.DeleteAutomationParams) (*protocol.DeleteAutomationResult, error) {
	var out protocol.DeleteAutomationResult
	return &out, c.Call(ctx, protocol.MethodDeleteAutomation, params, &out)
}

// ForkAutomation calls daemon.fork_automation.
func (c *Client) ForkAutomation(ctx context.Context, params protocol.ForkAutomationParams) (*protocol.ForkAutomationResult, error) {
	var out protocol.ForkAutomationResult
	return &out, c.Call(ctx, protocol.MethodForkAutomation, params, &out)
}

// ApplyAutomationConfig calls daemon.apply_automation_config.
func (c *Client) ApplyAutomationConfig(ctx context.Context, params protocol.ApplyAutomationConfigParams) (*protocol.ApplyAutomationConfigResult, error) {
	var out protocol.ApplyAutomationConfigResult
	return &out, c.Call(ctx, protocol.MethodApplyAutomationConfig, params, &out)
}

// UpdateAutomation calls daemon.update_automation.
func (c *Client) UpdateAutomation(ctx context.Context, params protocol.UpdateAutomationParams) (*protocol.UpdateAutomationResult, error) {
	var out protocol.UpdateAutomationResult
	return &out, c.Call(ctx, protocol.MethodUpdateAutomation, params, &out)
}

// SfListWorkstreams calls daemon.sf.list_workstreams.
func (c *Client) SfListWorkstreams(ctx context.Context, params protocol.SfListWorkstreamsParams) (*protocol.SfListWorkstreamsResult, error) {
	var out protocol.SfListWorkstreamsResult
	return &out, c.Call(ctx, protocol.MethodSfListWorkstreams, params, &out)
}

// SfGetWorkstream calls daemon.sf.get_workstream.
func (c *Client) SfGetWorkstream(ctx context.Context, params protocol.SfGetWorkstreamParams) (*protocol.SfGetWorkstreamResult, error) {
	var out protocol.SfGetWorkstreamResult
	return &out, c.Call(ctx, protocol.MethodSfGetWorkstream, params, &out)
}

// SfCreateWorkstream calls daemon.sf.create_workstream.
func (c *Client) SfCreateWorkstream(ctx context.Context, params protocol.SfCreateWorkstreamParams) (*protocol.SfCreateWorkstreamResult, error) {
	var out protocol.SfCreateWorkstreamResult
	return &out, c.Call(ctx, protocol.MethodSfCreateWorkstream, params, &out)
}

// SfUpdateWorkstream calls daemon.sf.update_workstream.
func (c *Client) SfUpdateWorkstream(ctx context.Context, params protocol.SfUpdateWorkstreamParams) (*protocol.SfUpdateWorkstreamResult, error) {
	var out protocol.SfUpdateWorkstreamResult
	return &out, c.Call(ctx, protocol.MethodSfUpdateWorkstream, params, &out)
}

// SfDeleteWorkstream calls daemon.sf.delete_workstream.
func (c *Client) SfDeleteWorkstream(ctx context.Context, params protocol.SfDeleteWorkstreamParams) (*protocol.SfDeleteWorkstreamResult, error) {
	var out protocol.SfDeleteWorkstreamResult
	return &out, c.Call(ctx, protocol.MethodSfDeleteWorkstream, params, &out)
}

// SfPublishWorkstreamContent calls daemon.sf.publish_workstream_content.
func (c *Client) SfPublishWorkstreamContent(ctx context.Context, params protocol.SfPublishWorkstreamContentParams) (*protocol.SfPublishWorkstreamContentResult, error) {
	var out protocol.SfPublishWorkstreamContentResult
	return &out, c.Call(ctx, protocol.MethodSfPublishWorkstreamContent, params, &out)
}

// SfHydrateWorkstreamContent calls daemon.sf.hydrate_workstream_content.
func (c *Client) SfHydrateWorkstreamContent(ctx context.Context, params protocol.SfHydrateWorkstreamContentParams) (*protocol.SfHydrateWorkstreamContentResult, error) {
	var out protocol.SfHydrateWorkstreamContentResult
	return &out, c.Call(ctx, protocol.MethodSfHydrateWorkstreamContent, params, &out)
}

// SfListSignals calls daemon.sf.list_signals.
func (c *Client) SfListSignals(ctx context.Context, params protocol.SfListSignalsParams) (*protocol.SfListSignalsResult, error) {
	var out protocol.SfListSignalsResult
	return &out, c.Call(ctx, protocol.MethodSfListSignals, params, &out)
}

// SfListChanges calls daemon.sf.list_changes.
func (c *Client) SfListChanges(ctx context.Context, params protocol.SfListChangesParams) (*protocol.SfListChangesResult, error) {
	var out protocol.SfListChangesResult
	return &out, c.Call(ctx, protocol.MethodSfListChanges, params, &out)
}

// SfListActivities calls daemon.sf.list_activities.
func (c *Client) SfListActivities(ctx context.Context, params protocol.SfListActivitiesParams) (*protocol.SfListActivitiesResult, error) {
	var out protocol.SfListActivitiesResult
	return &out, c.Call(ctx, protocol.MethodSfListActivities, params, &out)
}

// SfResolveActivityReview calls daemon.sf.resolve_activity_review.
func (c *Client) SfResolveActivityReview(ctx context.Context, params protocol.SfResolveActivityReviewParams) (*protocol.SfResolveActivityReviewResult, error) {
	var out protocol.SfResolveActivityReviewResult
	return &out, c.Call(ctx, protocol.MethodSfResolveActivityReview, params, &out)
}

// SfListEvents calls daemon.sf.list_events.
func (c *Client) SfListEvents(ctx context.Context, params protocol.SfListEventsParams) (*protocol.SfListEventsResult, error) {
	var out protocol.SfListEventsResult
	return &out, c.Call(ctx, protocol.MethodSfListEvents, params, &out)
}

// SfMarkEventsRead calls daemon.sf.mark_events_read.
func (c *Client) SfMarkEventsRead(ctx context.Context, params protocol.SfMarkEventsReadParams) (*protocol.SfMarkEventsReadResult, error) {
	var out protocol.SfMarkEventsReadResult
	return &out, c.Call(ctx, protocol.MethodSfMarkEventsRead, params, &out)
}

// SfMarkEventsUnread calls daemon.sf.mark_events_unread.
func (c *Client) SfMarkEventsUnread(ctx context.Context, params protocol.SfMarkEventsUnreadParams) (*protocol.SfMarkEventsUnreadResult, error) {
	var out protocol.SfMarkEventsUnreadResult
	return &out, c.Call(ctx, protocol.MethodSfMarkEventsUnread, params, &out)
}

// ListCrons calls daemon.list_crons.
func (c *Client) ListCrons(ctx context.Context, params protocol.ListCronsParams) (*protocol.ListCronsResult, error) {
	var out protocol.ListCronsResult
	return &out, c.Call(ctx, protocol.MethodListCrons, params, &out)
}

// CreateCron calls daemon.create_cron.
func (c *Client) CreateCron(ctx context.Context, params protocol.DaemonCreateCronRequestParams) (*protocol.CreateCronResult, error) {
	var out protocol.CreateCronResult
	return &out, c.Call(ctx, protocol.MethodCreateCron, params, &out)
}

// UpdateCron calls daemon.update_cron.
func (c *Client) UpdateCron(ctx context.Context, params protocol.UpdateCronParams) (*protocol.UpdateCronResult, error) {
	var out protocol.UpdateCronResult
	return &out, c.Call(ctx, protocol.MethodUpdateCron, params, &out)
}

// DeleteCron calls daemon.delete_cron.
func (c *Client) DeleteCron(ctx context.Context, params protocol.DeleteCronParams) (*protocol.DeleteCronResult, error) {
	var out protocol.DeleteCronResult
	return &out, c.Call(ctx, protocol.MethodDeleteCron, params, &out)
}

// HoldSessionCrons calls daemon.hold_session_crons.
func (c *Client) HoldSessionCrons(ctx context.Context, params protocol.HoldSessionCronsParams) (*protocol.HoldSessionCronsResult, error) {
	var out protocol.HoldSessionCronsResult
	return &out, c.Call(ctx, protocol.MethodHoldSessionCrons, params, &out)
}

// ResumeSessionCrons calls daemon.resume_session_crons.
func (c *Client) ResumeSessionCrons(ctx context.Context, params protocol.ResumeSessionCronsParams) (*protocol.ResumeSessionCronsResult, error) {
	var out protocol.ResumeSessionCronsResult
	return &out, c.Call(ctx, protocol.MethodResumeSessionCrons, params, &out)
}

// GetGitDiff calls daemon.get_git_diff.
func (c *Client) GetGitDiff(ctx context.Context, params protocol.GetGitDiffParams) (*protocol.GetGitDiffResult, error) {
	var out protocol.GetGitDiffResult
	return &out, c.Call(ctx, protocol.MethodGetGitDiff, params, &out)
}

// ListGitBranches calls daemon.list_git_branches.
func (c *Client) ListGitBranches(ctx context.Context, params protocol.ListGitBranchesParams) (*protocol.ListGitBranchesResult, error) {
	var out protocol.ListGitBranchesResult
	return &out, c.Call(ctx, protocol.MethodListGitBranches, params, &out)
}

// CheckoutGitBranch calls daemon.checkout_git_branch.
func (c *Client) CheckoutGitBranch(ctx context.Context, params protocol.CheckoutGitBranchParams) (*protocol.DaemonCheckoutGitBranchResult, error) {
	var out protocol.DaemonCheckoutGitBranchResult
	return &out, c.Call(ctx, protocol.MethodCheckoutGitBranch, params, &out)
}

// ResolvePullRequestStatuses calls daemon.resolve_pull_request_statuses.
func (c *Client) ResolvePullRequestStatuses(ctx context.Context, params protocol.ResolvePullRequestStatusesParams) (*protocol.ResolvePullRequestStatusesResult, error) {
	var out protocol.ResolvePullRequestStatusesResult
	return &out, c.Call(ctx, protocol.MethodResolvePullRequestStatuses, params, &out)
}

// GetGitBranchDivergence calls daemon.get_git_branch_divergence.
func (c *Client) GetGitBranchDivergence(ctx context.Context, params protocol.GetGitBranchDivergenceParams) (*protocol.DaemonGetGitBranchDivergenceResult, error) {
	var out protocol.DaemonGetGitBranchDivergenceResult
	return &out, c.Call(ctx, protocol.MethodGetGitBranchDivergence, params, &out)
}

// InspectMissionReadiness calls daemon.inspect_mission_readiness.
func (c *Client) InspectMissionReadiness(ctx context.Context, params protocol.InspectMissionReadinessParams) (*protocol.InspectMissionReadinessResult, error) {
	var out protocol.InspectMissionReadinessResult
	return &out, c.Call(ctx, protocol.MethodInspectMissionReadiness, params, &out)
}

// AcknowledgeMissionReadinessWarning calls daemon.acknowledge_mission_readiness_warning.
func (c *Client) AcknowledgeMissionReadinessWarning(ctx context.Context, params protocol.AcknowledgeMissionReadinessWarningParams) (*protocol.AcknowledgeMissionReadinessWarningResult, error) {
	var out protocol.AcknowledgeMissionReadinessWarningResult
	return &out, c.Call(ctx, protocol.MethodAcknowledgeMissionReadinessWarning, params, &out)
}

// GitPush calls daemon.git_push.
func (c *Client) GitPush(ctx context.Context, params protocol.GitPushParams) (*protocol.GitPushResult, error) {
	var out protocol.GitPushResult
	return &out, c.Call(ctx, protocol.MethodGitPush, params, &out)
}

// GitCommit calls daemon.git_commit.
func (c *Client) GitCommit(ctx context.Context, params protocol.GitCommitParams) (*protocol.GitCommitResult, error) {
	var out protocol.GitCommitResult
	return &out, c.Call(ctx, protocol.MethodGitCommit, params, &out)
}

// CreatePR calls daemon.create_pr.
func (c *Client) CreatePR(ctx context.Context, params protocol.CreatePRParams) (*protocol.CreatePRResult, error) {
	var out protocol.CreatePRResult
	return &out, c.Call(ctx, protocol.MethodCreatePR, params, &out)
}

// GetSemanticDiffCache calls daemon.get_semantic_diff_cache.
func (c *Client) GetSemanticDiffCache(ctx context.Context, params protocol.GetSemanticDiffCacheParams) (*protocol.GetSemanticDiffCacheResult, error) {
	var out protocol.GetSemanticDiffCacheResult
	return &out, c.Call(ctx, protocol.MethodGetSemanticDiffCache, params, &out)
}

// SaveSemanticDiffCache calls daemon.save_semantic_diff_cache.
func (c *Client) SaveSemanticDiffCache(ctx context.Context, params protocol.SaveSemanticDiffCacheParams) (*protocol.SaveSemanticDiffCacheResult, error) {
	var out protocol.SaveSemanticDiffCacheResult
	return &out, c.Call(ctx, protocol.MethodSaveSemanticDiffCache, params, &out)
}

// GenerateSemanticDiff calls daemon.generate_semantic_diff.
func (c *Client) GenerateSemanticDiff(ctx context.Context, params protocol.GenerateSemanticDiffParams) (*protocol.GenerateSemanticDiffResult, error) {
	var out protocol.GenerateSemanticDiffResult
	return &out, c.Call(ctx, protocol.MethodGenerateSemanticDiff, params, &out)
}

// GetProxyToken calls daemon.get_proxy_token.
func (c *Client) GetProxyToken(ctx context.Context, params json.RawMessage) (*protocol.GetProxyTokenResult, error) {
	var out protocol.GetProxyTokenResult
	return &out, c.Call(ctx, protocol.MethodGetProxyToken, params, &out)
}

// GetWorkspaceFileContent calls daemon.get_workspace_file_content.
func (c *Client) GetWorkspaceFileContent(ctx context.Context, params protocol.GetWorkspaceFileContentParams) (*protocol.GetWorkspaceFileContentResult, error) {
	var out protocol.GetWorkspaceFileContentResult
	return &out, c.Call(ctx, protocol.MethodGetWorkspaceFileContent, params, &out)
}

// WriteWorkspaceFileContent calls daemon.write_workspace_file_content.
func (c *Client) WriteWorkspaceFileContent(ctx context.Context, params protocol.WriteWorkspaceFileContentParams) (*protocol.WriteWorkspaceFileContentResult, error) {
	var out protocol.WriteWorkspaceFileContentResult
	return &out, c.Call(ctx, protocol.MethodWriteWorkspaceFileContent, params, &out)
}

// PushCwdFileToURL calls daemon.push_cwd_file_to_url.
func (c *Client) PushCwdFileToURL(ctx context.Context, params protocol.PushCwdFileToURLParams) (*protocol.PushCwdFileToURLResult, error) {
	var out protocol.PushCwdFileToURLResult
	return &out, c.Call(ctx, protocol.MethodPushCwdFileToURL, params, &out)
}

// PullURLToCwdFile calls daemon.pull_url_to_cwd_file.
func (c *Client) PullURLToCwdFile(ctx context.Context, params protocol.PullURLToCwdFileParams) (*protocol.PullURLToCwdFileResult, error) {
	var out protocol.PullURLToCwdFileResult
	return &out, c.Call(ctx, protocol.MethodPullURLToCwdFile, params, &out)
}
