// The read-only Markdown view of Memory, one file per Project Memory and one
// for the Global Memory, beside the database, for people and Obsidian. The
// database stays the source of truth; nothing here is ever read back.
import { chmodSync, mkdirSync, renameSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'
import {
  workspaceKey,
  type Category,
  type MemoryEntry,
  type MemorySlot,
  type MemoryStore,
} from './store'

/** In the order the file lists them: what must not be missed first. */
const HEADINGS: Record<Category, string> = {
  correction: 'Corrections',
  preference: 'Preferences',
  convention: 'Conventions',
  'tool-quirk': 'Tool quirks',
  failure: 'Failures',
  insight: 'Insights',
}

/** Where a Memory's Markdown file goes, relative to the Memory folder. */
export function markdownPath(slot: MemorySlot): string {
  if (slot.scope === 'global') return 'global.md'
  const name = basename(slot.workspace).replace(/[^\w.-]+/g, '-') || 'workspace'
  return join('projects', `${name}-${workspaceKey(slot.workspace).slice(0, 8)}.md`)
}

export function renderMarkdown(slot: MemorySlot, entries: readonly MemoryEntry[]): string {
  const title = slot.scope === 'global' ? 'Global Memory' : `Memory: ${slot.workspace}`
  const sections = (Object.keys(HEADINGS) as Category[]).flatMap((category) => {
    const inCategory = entries.filter((e) => e.category === category)
    if (inCategory.length === 0) return []
    const lines = inCategory.map((e) => `- ${e.text.replace(/\n+/g, ' ')} (\`${e.id}\`, ${e.day})`)
    return [`## ${HEADINGS[category]}\n\n${lines.join('\n')}\n`]
  })
  return [
    '<!-- Generated by Droi from its Memory database. Edits to this file are not read back; change Memory through Droid or Settings → Memory. -->',
    '',
    `# ${title}`,
    '',
    ...(sections.length > 0 ? sections : ['No entries yet.\n']),
  ].join('\n')
}

/** Rewrites the Markdown file of one Memory after a change to it. */
export function exportMarkdown(store: MemoryStore, slot: MemorySlot): string {
  const path = join(store.dir, markdownPath(slot))
  mkdirSync(join(path, '..'), { recursive: true })
  const tmp = `${path}.${process.pid}.tmp`
  writeFileSync(tmp, renderMarkdown(slot, store.list(slot)))
  chmodSync(tmp, 0o444)
  renameSync(tmp, path)
  return path
}
