import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { mkdtempSync, readFileSync, rmSync, statSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { openMemoryStore, type MemoryStore } from './store'
import { exportMarkdown, markdownPath } from './markdown'

let dir: string
let store: MemoryStore

beforeEach(() => {
  dir = mkdtempSync(join(tmpdir(), 'droi-memory-md-'))
  store = openMemoryStore(dir)
})

afterEach(() => {
  store.close()
  rmSync(dir, { recursive: true, force: true })
})

describe('Markdown export', () => {
  const app = { scope: 'project' as const, workspace: '/Users/dev/my app' }

  it('writes one read-only file per Memory, grouped by category, corrections first', () => {
    const convention = store.add(app, 'convention', 'Tests sit next to the code')
    store.add(app, 'correction', 'Use pnpm, not npm')
    if (!convention.ok) throw new Error(convention.reason)
    const path = exportMarkdown(store, app)
    expect(path).toBe(join(dir, markdownPath(app)))
    expect(markdownPath(app)).toMatch(/^projects\/my-app-[0-9a-f]{8}\.md$/)
    const text = readFileSync(path, 'utf8')
    expect(text).toMatch(/^<!-- Generated by Droi .*not read back/)
    expect(text).toContain('# Memory: /Users/dev/my app')
    expect(text.indexOf('## Corrections')).toBeLessThan(text.indexOf('## Conventions'))
    expect(text).toContain(
      `- Tests sit next to the code (\`${convention.entry.id}\`, ${convention.entry.day})`,
    )
    expect(statSync(path).mode & 0o777).toBe(0o444)
  })

  it('rewrites the file after a change, read-only or not', () => {
    const added = store.add({ scope: 'global' }, 'preference', 'Answer tersely')
    if (!added.ok) throw new Error(added.reason)
    exportMarkdown(store, { scope: 'global' })
    store.remove(added.entry.id)
    const path = exportMarkdown(store, { scope: 'global' })
    expect(path).toBe(join(dir, 'global.md'))
    expect(readFileSync(path, 'utf8')).toContain('No entries yet.')
  })
})
