// The read-only Markdown view of Memory, one file per Project Memory and one
// for the Global Memory, beside the database, for people and Obsidian. The
// database stays the source of truth; nothing here is ever read back.

package memory

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// In the order the file lists them: what must not be missed first.
var headings = []struct {
	category Category
	title    string
}{
	{CategoryCorrection, "Corrections"},
	{CategoryPreference, "Preferences"},
	{CategoryConvention, "Conventions"},
	{CategoryToolQuirk, "Tool quirks"},
	{CategoryFailure, "Failures"},
	{CategoryInsight, "Insights"},
}

var (
	unsafeName = regexp.MustCompile(`[^\w.-]+`)
	newlines   = regexp.MustCompile(`\n+`)
)

// MarkdownPath is where a Memory's Markdown file goes, relative to the Memory
// folder.
func MarkdownPath(slot Slot) string {
	if slot.Scope == ScopeGlobal {
		return "global.md"
	}
	base := filepath.Base(slot.Workspace)
	if base == "/" || base == "." {
		base = "" // Node's basename of "/" or ""
	}
	name := unsafeName.ReplaceAllString(base, "-")
	if name == "" {
		name = "workspace"
	}
	return filepath.Join("projects", name+"-"+WorkspaceKey(slot.Workspace)[:8]+".md")
}

// RenderMarkdown is the Markdown file of one Memory.
func RenderMarkdown(slot Slot, entries []Entry) string {
	title := "Global Memory"
	if slot.Scope != ScopeGlobal {
		title = "Memory: " + slot.Workspace
	}
	var sections []string
	for _, h := range headings {
		var lines []string
		for _, e := range entries {
			if e.Category == h.category {
				lines = append(lines, fmt.Sprintf("- %s (`%s`, %s)", newlines.ReplaceAllString(e.Text, " "), e.ID, e.Day))
			}
		}
		if len(lines) > 0 {
			sections = append(sections, "## "+h.title+"\n\n"+strings.Join(lines, "\n")+"\n")
		}
	}
	if len(sections) == 0 {
		sections = []string{"No entries yet.\n"}
	}
	return strings.Join(append([]string{
		"<!-- Generated by Droi from its Memory database. Edits to this file are not read back; change Memory through Droid or Settings → Memory. -->",
		"",
		"# " + title,
		"",
	}, sections...), "\n")
}

// ExportMarkdown rewrites the Markdown file of one Memory after a change to it
// and answers its path.
func ExportMarkdown(store *Store, slot Slot) (string, error) {
	path := filepath.Join(store.Dir(), MarkdownPath(slot))
	if err := os.MkdirAll(filepath.Dir(path), 0o777); err != nil {
		return "", err
	}
	entries, err := store.List(slot, "")
	if err != nil {
		return "", err
	}
	tmp := fmt.Sprintf("%s.%d.tmp", path, os.Getpid())
	if err := os.WriteFile(tmp, []byte(RenderMarkdown(slot, entries)), 0o666); err != nil {
		return "", err
	}
	if err := os.Chmod(tmp, 0o444); err != nil {
		return "", err
	}
	return path, os.Rename(tmp, path)
}
