package memory

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

func evalSymlinks(path string) (string, error) { return filepath.EvalSymlinks(path) }

// Secrets are built from parts so the source holds none.
var secretTexts = map[string]string{
	"an OpenAI key":         "use sk-" + strings.Repeat("aB3", 12) + " for the tests",
	"a Factory key":         "FACTORY_API_KEY is fk-" + strings.Repeat("a1B2", 7),
	"an AWS access key":     "the key AKIA" + "IOSFODNN7EXAMPLE works",
	"a GitHub token":        "push with ghp_" + strings.Repeat("aB3d", 9),
	"a Slack token":         "xoxb-" + "1234567890-abcdefghijkl",
	"a bearer token":        "Authorization: Bearer abcdefghijklmnopqrstuvwxyz.123456",
	"a JWT":                 "token eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dozjgNryP4J3jVmNHl0w5N",
	"a private key":         "-----BEGIN OPENSSH " + "PRIVATE KEY-----\nb3BlbnNzaC1rZXktdjEAAAAA",
	"a password assignment": "the staging db uses password=hunter2",
	"an api_key assignment": `api_key: "0123456789abcdef0123"`,
}

func TestFindSecretRefusesCredentials(t *testing.T) {
	for label, text := range secretTexts {
		if FindSecret(text) == "" {
			t.Errorf("lets %s through", label)
		}
	}
}

func TestFindSecretLetsOrdinaryTextThrough(t *testing.T) {
	for _, text := range []string{
		"Run pnpm check && pnpm test before committing.",
		"The user prefers answers in Chinese.",
		"Passwords are hashed with argon2 in src/auth.",
		"Do not use the sk- prefix check in tests.",
		"The token budget is 200k.",
	} {
		if reason := FindSecret(text); reason != "" {
			t.Errorf("refuses %q: %s", text, reason)
		}
	}
}

func TestFindSecretNamesWhatItFoundWithoutRepeatingIt(t *testing.T) {
	reason := FindSecret("password=hunter2")
	if !strings.Contains(strings.ToLower(reason), "password") || strings.Contains(reason, "hunter2") {
		t.Fatalf("reason %q", reason)
	}
}

func similarEntry(id, text string) Entry {
	return Entry{ID: id, Scope: ScopeProject, Workspace: "/Users/dev/app", Category: CategoryConvention, Day: "2026-10-03", Text: text}
}

var similarMemory = []Entry{
	similarEntry("release1", `Release procedure: bump "version" in apps/desktop/package.json, add a CHANGELOG.md section, commit "chore(release): X.Y.Z", tag vX.Y.Z and push main and the tag.`),
	similarEntry("vitest01", "Unit tests sit next to the code as *.test.ts and run with vitest from the root."),
	similarEntry("wsl00001", "win.myhome is WSL2 Ubuntu with systemd; the multica daemon runs as a user service."),
	similarEntry("cover001", "小红书视频封面用 4:3，关键内容放在中间安全区。"),
	similarEntry("voice001", "中文讲解视频的配音用 Gemini 的 Puck 声音，语速 1.25 倍。"),
}

func ids(entries []Entry) []string {
	out := []string{}
	for _, e := range entries {
		out = append(out, e.ID)
	}
	return out
}

func TestSimilarityTokens(t *testing.T) {
	eq(t, SimilarityTokens("Use pnpm, a tool"), []string{"use", "pnpm", "tool"})
	eq(t, SimilarityTokens("视频封面"), []string{"视频", "频封", "封面"})
	eq(t, SimilarityTokens("用 x"), []string{"用"})
}

func TestSimilarEntriesFindsAnEntryThatSaysTheSameThingInOtherWords(t *testing.T) {
	found := SimilarEntries(`Releasing Droi: a "chore(release): X.Y.Z" commit bumps apps/desktop/package.json version and prepends a CHANGELOG.md entry, then tag vX.Y.Z and push main plus the tag.`, similarMemory, SimilarMin, SimilarLimit)
	eq(t, ids(found), []string{"release1"})
}

func TestSimilarEntriesFindsAChineseEntryAboutTheSameSubject(t *testing.T) {
	eq(t, ids(SimilarEntries("小红书封面改成 3:4 竖版，关键内容仍放中间。", similarMemory, SimilarMin, SimilarLimit)), []string{"cover001"})
}

func TestSimilarEntriesFindsNothingForAnUnrelatedFact(t *testing.T) {
	eq(t, ids(SimilarEntries("The Phone App is pinned to Expo SDK 57.", similarMemory, SimilarMin, SimilarLimit)), []string{})
	eq(t, ids(SimilarEntries("", similarMemory, SimilarMin, SimilarLimit)), []string{})
	eq(t, ids(SimilarEntries("anything", nil, SimilarMin, SimilarLimit)), []string{})
}

func TestSimilarEntriesReturnsAtMostTheLimitBestFirst(t *testing.T) {
	copies := []Entry{similarEntry("a", "pnpm check runs lint"), similarEntry("b", "pnpm check runs lint and format")}
	eq(t, ids(SimilarEntries("pnpm check runs lint", copies, SimilarMin, 1)), []string{"a"})
}

func TestMarkdownWritesOneReadOnlyFilePerMemoryCorrectionsFirst(t *testing.T) {
	s, dir := openTestStore(t)
	app := Slot{Scope: ScopeProject, Workspace: "/Users/dev/my app"}
	convention := add(t, s, app, "Tests sit next to the code", CategoryConvention)
	add(t, s, app, "Use pnpm, not npm", CategoryCorrection)
	path := must[string](t)(ExportMarkdown(s, app))
	eq(t, path, filepath.Join(dir, MarkdownPath(app)))
	if !regexp.MustCompile(`^projects/my-app-[0-9a-f]{8}\.md$`).MatchString(MarkdownPath(app)) {
		t.Fatalf("path %q", MarkdownPath(app))
	}
	b := must[[]byte](t)(os.ReadFile(path))
	text := string(b)
	if !regexp.MustCompile(`^<!-- Generated by Droi .*not read back`).MatchString(text) {
		t.Fatal(text)
	}
	if !strings.Contains(text, "# Memory: /Users/dev/my app") || strings.Index(text, "## Corrections") > strings.Index(text, "## Conventions") {
		t.Fatal(text)
	}
	if !strings.Contains(text, "- Tests sit next to the code (`"+convention.ID+"`, "+convention.Day+")") {
		t.Fatal(text)
	}
	info := must[os.FileInfo](t)(os.Stat(path))
	eq(t, info.Mode().Perm(), os.FileMode(0o444))
}

func TestMarkdownRewritesTheFileAfterAChangeReadOnlyOrNot(t *testing.T) {
	s, dir := openTestStore(t)
	added := add(t, s, GlobalSlot, "Answer tersely", CategoryPreference)
	must[string](t)(ExportMarkdown(s, GlobalSlot))
	must[bool](t)(s.Remove(added.ID))
	path := must[string](t)(ExportMarkdown(s, GlobalSlot))
	eq(t, path, filepath.Join(dir, "global.md"))
	if !strings.Contains(string(must[[]byte](t)(os.ReadFile(path))), "No entries yet.") {
		t.Fatal("not rewritten")
	}
}

func TestMarkdownRendersTheWholeFile(t *testing.T) {
	got := RenderMarkdown(GlobalSlot, []Entry{
		{ID: "aaaaaaaa", Scope: ScopeGlobal, Category: CategoryInsight, Day: "2026-10-01", Text: "two\n\nlines"},
		{ID: "bbbbbbbb", Scope: ScopeGlobal, Category: CategoryCorrection, Day: "2026-10-02", Text: "no emojis"},
	})
	want := "<!-- Generated by Droi from its Memory database. Edits to this file are not read back; change Memory through Droid or Settings → Memory. -->\n\n# Global Memory\n\n## Corrections\n\n- no emojis (`bbbbbbbb`, 2026-10-02)\n\n## Insights\n\n- two lines (`aaaaaaaa`, 2026-10-01)\n"
	eq(t, got, want)
}

func TestParseTranscriptKeepsPromptsAndProseOnly(t *testing.T) {
	jsonl := strings.Join([]string{
		`{"type":"session_start","id":"s","cwd":"/w"}`,
		`{"type":"message","id":"context-1","message":{"role":"user","content":[{"type":"text","text":"<system-reminder>skills</system-reminder>"}]}}`,
		`{"type":"message","message":{"role":"user","content":[{"type":"text","text":"Fix the login bug"},{"type":"text","text":"<system-reminder>date</system-reminder>"}]}}`,
		`{"type":"message","message":{"role":"assistant","content":[{"type":"thinking","thinking":"hmm"},{"type":"text","text":"Looking at auth.ts"},{"type":"tool_use","id":"t","name":"Read","input":{}}]}}`,
		`{"type":"message","message":{"role":"user","content":[{"type":"tool_result","content":"file"}]}}`,
		`{"type":"todo_state","todos":[]}`,
		"not json",
		`{"type":"message","message":{"role":"user","content":"不对，是 session.ts"}}`,
	}, "\n")
	turns := ParseTranscript(jsonl)
	eq(t, turns, []Turn{{"user", "Fix the login bug"}, {"assistant", "Looking at auth.ts"}, {"user", "不对，是 session.ts"}})
	eq(t, UserPromptCount(turns), 2)
}

func writeSessionFile(t *testing.T, dir, folder, id string, lines ...string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Join(dir, folder), 0o777); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, folder, id+".jsonl"), []byte(strings.Join(lines, "\n")), 0o666); err != nil {
		t.Fatal(err)
	}
}

func writeFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0o666); err != nil {
		t.Fatal(err)
	}
}

func TestFindSessionWorkspaceReadsTheSessionStartLine(t *testing.T) {
	dir := t.TempDir()
	writeSessionFile(t, dir, "-Users-dev-other", "aaa", `{"type":"session_start","cwd":"/Users/dev/other"}`)
	writeSessionFile(t, dir, "-Users-dev-app", "bbb", `{"type":"session_start","id":"bbb","cwd":"/Users/dev/app"}`, `{"type":"message","message":{"role":"user","content":[]}}`)
	eq(t, FindSessionWorkspace(dir, "bbb"), "/Users/dev/app")
}

func TestFindSessionWorkspaceAnswersNothingForWhatItCannotPlace(t *testing.T) {
	dir := t.TempDir()
	writeSessionFile(t, dir, "-x", "ccc", `{"type":"message"}`)
	eq(t, FindSessionWorkspace(dir, "missing"), "")
	eq(t, FindSessionWorkspace(dir, "../etc/passwd"), "")
	eq(t, FindSessionWorkspace(dir, "ccc"), "")
	eq(t, FindSessionWorkspace(filepath.Join(dir, "nope"), "ccc"), "")
}

func TestSessionsDirFollowsFactoryHomeOverride(t *testing.T) {
	env := func(key string) (string, bool) {
		if key == "FACTORY_HOME_OVERRIDE" {
			return "/tmp/f", true
		}
		return "", false
	}
	eq(t, SessionsDir(env), "/tmp/f/sessions")
}

func TestIsMemorySessionTranscriptReadsTheTag(t *testing.T) {
	dir := t.TempDir()
	writeSessionFile(t, dir, "-w", "mem", `{"type":"session_start","cwd":"/w"}`)
	transcript := FindSessionTranscript(dir, "mem")
	eq(t, SessionSettingsFile(transcript), filepath.Join(dir, "-w", "mem.settings.json"))
	eq(t, IsMemorySessionTranscript(transcript), false)
	writeFile(t, SessionSettingsFile(transcript), `{"tags":[{"name":"droi.draft"}]}`)
	eq(t, IsMemorySessionTranscript(transcript), false)
	writeFile(t, SessionSettingsFile(transcript), `{"tags":[{"name":"droi.memory"}]}`)
	eq(t, IsMemorySessionTranscript(transcript), true)
}

func TestIsScratchSessionTranscriptReadsTheInheritedTag(t *testing.T) {
	dir := t.TempDir()
	writeSessionFile(t, dir, "-Users-me--droi-chats-2026-09-30-25e965", "chat", `{"type":"session_start","cwd":"/Users/me/.droi/chats/2026-09-30-25e965"}`)
	transcript := FindSessionTranscript(dir, "chat")
	eq(t, IsScratchSessionTranscript(transcript), false)
	writeFile(t, SessionSettingsFile(transcript), `{"tags":[{"name":"droi.scratch"},{"name":"droi.continues","metadata":{"parent":"p"}}]}`)
	eq(t, IsScratchSessionTranscript(transcript), true)
	eq(t, IsMemorySessionTranscript(transcript), false)
}
